apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-proxy
  namespace: imagesizegatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray-proxy
  template:
    metadata:
      labels:
        app: v2ray-proxy
    spec:
      containers:
        - name: v2ray
          image: v2fly/v2fly-core:latest
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 1080
              name: socks
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/v2ray/config.json
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: v2ray-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
  namespace: imagesizegatekeeper
data:
  config.json: |
    {
      "log": {
        "loglevel": "info"
      },
      "inbounds": [
        {
          "port": 1080,
          "protocol": "socks",
          "settings": {
            "auth": "noauth",
            "udp": true
          },
          "tag": "socks"
        },
        {
          "port": 8080,
          "protocol": "http",
          "settings": {},
          "tag": "http"
        }
      ],
      "outbounds": [
        {
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "8.210.251.224",
                "port": 43370,
                "users": [
                  {
                    "id": "357045b4-55c1-4100-82d0-8a1bfa72b77e",
                    "encryption": "none"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "grpc",
            "security": "reality",
            "realitySettings": {
              "fingerprint": "chrome",
              "serverName": "www.icloud.com",
              "publicKey": "8ppnx1gEZ6mrltDa7DWdSb_R3N1Un8Mq5J_bFoqjbRU",
              "shortId": "4470ed1f93e72282",
              "spiderX": "/"
            }
          },
          "tag": "proxy"
        },
        {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
        }
      ],
      "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
          {
            "type": "field",
            "inboundTag": ["socks", "http"],
            "outboundTag": "proxy"
          }
        ]
      }
    }
