apiVersion: v1
kind: Service
metadata:
  name: v2ray-proxy
  namespace: imagesizegatekeeper
spec:
  selector:
    app: v2ray-proxy
  ports:
    - name: socks
      port: 1080
      targetPort: socks
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
