apiVersion: v1
kind: ConfigMap
metadata:
  name: image-size-gatekeeper-config
  namespace: image-size-gatekeeper
data:
  config.yaml: |
    # 服务器配置
    port: 8443
    tlsCertFile: "/etc/webhook/certs/tls.crt"
    tlsKeyFile: "/etc/webhook/certs/tls.key"
    logLevel: "info"
    
    # 代理配置
    proxyEnabled: false
    proxyURL: ""  # 例如 "socks5h://username:password@host:port"
    
    # 命名空间限制配置
    namespaceRestrictions:
      # 精确匹配的命名空间
      default:
        enabled: true
        maxSizeMB: 1000
        requireOriginalRegistry: true
      
      test:
        enabled: true
        maxSizeMB: 500
        requireOriginalRegistry: true
        
      # 正则表达式匹配的命名空间
      "^user-.*$":
        enabled: true
        maxSizeMB: 300
        requireOriginalRegistry: true
        isRegex: true  # 启用正则表达式匹配
        
      "^team-.*$":
        enabled: true
        maxSizeMB: 800
        requireOriginalRegistry: false
        isRegex: true  # 启用正则表达式匹配 