apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-size-gatekeeper
  namespace: image-size-gatekeeper
  labels:
    app: image-size-gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-size-gatekeeper
  template:
    metadata:
      labels:
        app: image-size-gatekeeper
    spec:
      containers:
        - name: webhook
          image: demo.52013120.xyz/skopeo-webhook:latest
          imagePullPolicy: Always
          args:
            - "--config=/etc/webhook/config/config.yaml"
          volumeMounts:
            - name: webhook-config
              mountPath: /etc/webhook/config
              readOnly: true
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          ports:
            - containerPort: 8443
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: webhook-config
          configMap:
            name: image-size-gatekeeper-config
        - name: webhook-certs
          secret:
            secretName: webhook-tls 