apiVersion: v1
kind: Secret
metadata:
  name: imagesizegatekeeper-secrets
  namespace: imagesizegatekeeper
type: Opaque
stringData:
  # 代理URL
  proxy-url: ""

  # Docker Hub认证信息
  "registry_credentials_docker.io": "your_dockerhub_username:your_dockerhub_password"
