apiVersion: v1
kind: Secret
metadata:
  name: imagesizegatekeeper-secrets
  namespace: imagesizegatekeeper
type: Opaque
stringData:
  # 代理URL
  proxy-url: "vless://fc0bd225-519d-4f55-a346-bb15ae0628ce@8.210.251.224:8443?type=grpc&serviceName=&authority=&security=reality&pbk=8ppnx1gEZ6mrltDa7DWdSb_R3N1Un8Mq5J_bFoqjbRU&fp=chrome&sni=www.icloud.com&sid=4470ed1f93e72282&spx=%2F#HK-hk"

  # Docker Hub认证信息
  "registry-credentials/docker.io": "your_dockerhub_username:your_dockerhub_password"

  # GCR认证信息
  "registry-credentials/gcr.io": "oauth2accesstoken:your_gcp_token"
