apiVersion: v1
kind: Secret
metadata:
  name: imagesizegatekeeper-secrets
  namespace: imagesizegatekeeper
type: Opaque
stringData:
  # 仓库认证信息（用户名:密码）
  registry_credentials_docker.io: "username:password"
  registry_credentials_ghcr.io: "github-username:github-token"
  # 代理URL
  proxy-url: "socks5://v2ray-proxy.imagesizegatekeeper.svc.cluster.local:1080"
  # 代理类型 (none, http, socks5)
  proxy-type: "socks5"
