---
# 先创建一个自签名的根证书颁发机构
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# 使用自签名颁发机构创建CA证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h # 5年
  secretName: webhook-ca
  commonName: "webhook-ca"
  subject:
    organizations:
      - "ImageSizeGatekeeper"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# 使用生成的CA证书创建CA签发者
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: webhook-ca-issuer
spec:
  ca:
    secretName: webhook-ca
