apiVersion: v1
kind: Service
metadata:
  name: imagesizegatekeeper
  namespace: imagesizegatekeeper
  labels:
    app: imagesizegatekeeper
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: imagesizegatekeeper
