apiVersion: v1
kind: Service
metadata:
  name: image-size-gatekeeper
  namespace: image-size-gatekeeper
  labels:
    app: image-size-gatekeeper
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: image-size-gatekeeper 