apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: image-size-gatekeeper
  labels:
    app: image-size-gatekeeper
webhooks:
  - name: image-size-validation.k8s.io
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 30
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: image-size-gatekeeper
        namespace: image-size-gatekeeper
        path: "/webhook"
      caBundle: ${CA_BUNDLE}  # 这里需要替换为CA证书的Base64编码
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "image-size-gatekeeper"] 